// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// AIT_DMN
double AIT_DMN(Rcpp::NumericMatrix x, Rcpp::NumericVector y, Rcpp::NumericVector yu, double lambda);
RcppExport SEXP _AIT_AIT_DMN(SEXP xSEXP, SEXP ySEXP, SEXP yuSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type yu(yuSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(AIT_DMN(x, y, yu, lambda));
    return rcpp_result_gen;
END_RCPP
}
// AIT_DMN_slice
Rcpp::List AIT_DMN_slice(Rcpp::NumericMatrix x, Rcpp::NumericVector y, Rcpp::NumericVector yu, double lambda);
RcppExport SEXP _AIT_AIT_DMN_slice(SEXP xSEXP, SEXP ySEXP, SEXP yuSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type yu(yuSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(AIT_DMN_slice(x, y, yu, lambda));
    return rcpp_result_gen;
END_RCPP
}
// AIT_MN
double AIT_MN(Rcpp::NumericMatrix x, Rcpp::NumericVector y, Rcpp::NumericVector yu, double lambda);
RcppExport SEXP _AIT_AIT_MN(SEXP xSEXP, SEXP ySEXP, SEXP yuSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type yu(yuSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(AIT_MN(x, y, yu, lambda));
    return rcpp_result_gen;
END_RCPP
}
// AIT_MN_slice
Rcpp::List AIT_MN_slice(Rcpp::NumericMatrix x, Rcpp::NumericVector y, Rcpp::NumericVector yu, double lambda);
RcppExport SEXP _AIT_AIT_MN_slice(SEXP xSEXP, SEXP ySEXP, SEXP yuSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type yu(yuSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(AIT_MN_slice(x, y, yu, lambda));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AIT_AIT_DMN", (DL_FUNC) &_AIT_AIT_DMN, 4},
    {"_AIT_AIT_DMN_slice", (DL_FUNC) &_AIT_AIT_DMN_slice, 4},
    {"_AIT_AIT_MN", (DL_FUNC) &_AIT_AIT_MN, 4},
    {"_AIT_AIT_MN_slice", (DL_FUNC) &_AIT_AIT_MN_slice, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_AIT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
