# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AIT_DMN <- function(x, y, yu, lambda) {
    .Call('_AIT_AIT_DMN', PACKAGE = 'AIT', x, y, yu, lambda)
}

AIT_DMN_slice <- function(x, y, yu, lambda) {
    .Call('_AIT_AIT_DMN_slice', PACKAGE = 'AIT', x, y, yu, lambda)
}

AIT_MN <- function(x, y, yu, lambda) {
    .Call('_AIT_AIT_MN', PACKAGE = 'AIT', x, y, yu, lambda)
}

AIT_MN_slice <- function(x, y, yu, lambda) {
    .Call('_AIT_AIT_MN_slice', PACKAGE = 'AIT', x, y, yu, lambda)
}

